# https://en.wikipedia.org/wiki/Computer_programming#Readability_of_source_code



# EXAMPLE 1:
''' 
#PE29.py 
How many distinct terms are in the sequence generated by 
a^b for 2 <= a <= 100 and 2 <= b <= 100? 
'''

# Too dense -- less readable:
print len(set([a**b for b in range(2, 101) for a in range(2, 101)]))


# Less dense, less abstract -- more readable:
terms = [a**b for b in range(2, 101) for a in range(2, 101)]
print len(set(terms))

